# Generated by Django 6.0.3 on 2026-03-21 23:37

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('phone', models.CharField(blank=True, default='', help_text='Optional if email is provided; at least one contact method is required.', max_length=32, verbose_name='phone number')),
                ('email', models.EmailField(blank=True, default='', help_text='Optional if phone is provided; at least one contact method is required.', max_length=254, verbose_name='email address')),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('medical_history', models.TextField(blank=True)),
                ('allergies', models.TextField(blank=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='patients', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'patients',
                'indexes': [models.Index(fields=['name'], name='patients_name_idx'), models.Index(fields=['phone'], name='patients_phone_idx'), models.Index(fields=['email'], name='patients_email_idx')],
            },
        ),
    ]
