# Generated by Django 6.0.3 on 2026-03-26 18:23

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0002_soft_delete'),
        ('patients', '0002_soft_delete'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='appointment',
            name='appts_patient_idx',
        ),
        migrations.AddIndex(
            model_name='appointment',
            index=models.Index(fields=['patient', 'scheduled_at'], name='appts_patient_sched_idx'),
        ),
    ]
